### ISSUE TITLE
Merge php-mime-mail-parser

### ISSUE THREAD

**Issue by eXorus** [message/php-mime-mail-parser#12]
Hello,

Code Google will be closed soon and we worked hard to fork it so I would like to ask if you want to merge our php-mime-mail-parser in one ?

According to this link http://fabien.potencier.org/article/75/about-personal-github-accounts
I would like to create a new Github Organization php-mime-mail-parser to maintain this fork.

What do you think about it ?

My fork : https://github.com/eXorus/php-mime-mail-parser

**Comment by message** [comment]
Hey Vincent, 

Yes, I would love that. I think we should use your version as base since it's almost fully tested.

**Comment by eXorus** [comment]
Done
https://github.com/php-mime-mail-parser/php-mime-mail-parser
 and you are also owner.
Welcome !!

**Comment by duncan3dc** [comment]
@message Please could you [abandon](https://twitter.com/seldaek/status/492060247788617728) the package on [packagist](https://packagist.org/packages/messaged/php-mime-mail-parser), and add a note advising that it's been merged with `exorus/php-mime-mail-parser`?

**Comment by message** [comment]
@duncan3dc done.

**Comment by eXorus** [comment]
Hi message,

could you abandon the package on packagist with php-mime-mail-parser/php-mime-mail-parser on replacement.

Thanks
